

# 查询
https://exm-mayuan-ans.chaoxing.com/selftest/chapter-test
?courseId=215779000
&classId=1718
&cpi=154457568

# 单元测试 <绪论>
# 开始考试
https://exm-mayuan-ans.chaoxing.com/selftest/start-test
?courseId=215779000
&classId=1718
&cpi=154457568
&dirid=68773828


# 提交一个答案
https://exm-mayuan-ans.chaoxing.com/exam/test/reVersionSubmitTestNew
?classId=1718
&courseId=215779000
&cpi=154457568
&testPaperId=124904
&testUserRelationId=301727
&tempSave=true
&pos=aa54d32744804c9dcf000c0e04
&rd=0.40079002039296774
&value=(444|843)
&qid=90
&_edt=1606886979113266
&version=1

# 提交答案
https://exm-mayuan-ans.chaoxing.com/exam/test/reVersionSubmitTestNew
?classId=1718
&courseId=215779000
&testPaperId=124904
&testUserRelationId=301727
&cpi=154457568
&tempSave=false
&pos=b609a21655f735413a2d00d3a3d7
&rd=0.7138700386281238
&value=(470|1008)
&qid=
&_edt=1606887019978264
&version=1

# 查看答案
https://exm-mayuan-ans.chaoxing.com/exam/phone/look-detail
?courseId=215779000
&classId=1718
&examId=124904
&examAnswerId=301727  # 随便6位数
&protocol_v=1




# 章节自测一

https://exm-mayuan-ans.chaoxing.com/selftest/start-test
?courseId=215779000
&classId=1718
&cpi=154457568
&dirid=68773832


examId = re.search('examId: \'(\d{6})\'', "examId: '123456'", re.I)
https://exm-mayuan-ans.chaoxing.com/selftest/start-test
?courseId=215779000
&classId=1718
&cpi=154457568
&dirid=68773852

https://exm-mayuan-ans.chaoxing.com/selftest/start-test-action
?courseId=215779000
&classId=1718
&examId=124930
&source=0
&examAnswerId=0
&cpi=154457568
&dirid=68773832
&keyboardDisplayRequiresUserAction=1
&imei=96935f7136ad4b0a8d7965f4fa72fbcb

https://exm-mayuan-ans.chaoxing.com/exam/test/reVersionTestStartNew
?courseId=215779000
&classId=1718
&tId=124930
&id=0&source=0
&p=1&isphone=true
&tag=1
&ut=s
&cpi=154457568
&imei=96935f7136ad4b0a8d7965f4fa72fbcb
&enc=c55a4640270dafc9f3224e8ff3f416e6
&keyboardDisplayRequiresUserAction=1
&protocol_v=1

https://exm-mayuan-ans.chaoxing.com/exam/phone/look-detail
?courseId=215779000
&classId=1718
&examId=124930
&examAnswerId=301964
&protocol_v=1



https://exm-mayuan-ans.chaoxing.com/selftest/start-test-action?courseId=215779000&classId=1718&examId=124931&source=0&examAnswerId=0&cpi=154457568&dirid=68773832&keyboardDisplayRequiresUserAction=1&imei=96935f7136ad4b0a8d7965f4fa72fbcb